export enum OrderStatus {
    PENDING_PAYMENT = "PENDING_PAYMENT",
    PROCESSING_PAYMENT = "PROCESSING_PAYMENT",
    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED",
    PAYMENT_DECLINED = "PAYMENT_DECLINED",
    PAYMENT_CANCELLED = "PAYMENT_CANCELLED",
    PENDING_SHIPPING = "PENDING_SHIPPING",
    CONFIRMED = "CONFIRMED",
    SHIPPED = "SHIPPED",
    DELIVERED = "DELIVERED",
    CANCELED = "CANCELED",
    REFOUNDED = "REFOUNDED",
  }