import type { Metadata } from 'next';
import { Geist, Geist_Mono, Orbitron } from 'next/font/google';

import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { QueryContext } from '@/contexts/queryContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const orbitron = Orbitron({
  variable: '--font-orbitron',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${orbitron.variable} antialiased dark`}
      >
        <QueryContext>
          {children}
          <Toaster />
        </QueryContext>
      </body>
    </html>
  );
}
